export const SAVE_TO_FAVORITES = 'SAVE_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const START_PRODUCTS_LOADING = 'START_PRODUCTS_LOADING';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const STOP_PRODUCTS_LOADING = 'STOP_PRODUCTS_LOADING';
