export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const PRODUCTS_LOAD = 'PRODUCTS_LOAD';
export const SINGLE_PRODUCT_LOAD = 'SINGLE_PRODUCT_LOAD';

export const STOP_PRODUCTS_LOADING = 'STOP_PRODUCTS_LOADING';
export const START_PRODUCTS_LOADING = 'START_PRODUCTS_LOADING';

export const ERROR_GET_PRODUCTS = 'ERROR_GET_PRODUCTS';
export const ERROR_GET_SINGLE_PRODUCT = 'ERROR_GET_SINGLE_PRODUCT';
